LOCAL_BL_FROM {
  type = "from";
  filter = "email:domain";
  map = "${LOCAL_CONFDIR}/local.d/local_bl_from.map.inc";
  symbol = "LOCAL_BL_FROM";
  description = "Local From blacklist";
}

AUTO_PHISH_DOMAIN_BLOCK {
  type = "from";
  filter = "email:domain";
  map = "/var/lib/rspamd/auto_phish_domains.map";
  symbol = "AUTO_PHISH_DOMAIN_BLOCK";
  description = "Domain auto-blocked after phishing detection";
}

LOCAL_WL_DOMAIN {
  type = "from";
  filter = "email:domain";
  map = "${LOCAL_CONFDIR}/local.d/maps.d/whitelisted_domains.map";
  symbol = "LOCAL_WL_DOMAIN";
  description = "Whitelisted sender domains";
}
