// src/store/useGeoAuthStore.js
import { create } from 'zustand';

const useGeoAuthStore = create((set) => ({
  geoSettings: [],
  setGeoSettings: (geoSettings) => set({ geoSettings }),
  geoExceptions: [],
  setGeoExceptions: (geoExceptions) => set({ geoExceptions }),
  geoBans: [],
  setGeoBans: (geoBans) => set({ geoBans }),
  geoRegions: [],
  setGeoRegions: (geoRegions) => set({ geoRegions }),
  sshAllowedCountries: '',
  setSshAllowedCountries: (sshAllowedCountries) => set({ sshAllowedCountries }),
  sshAllowedRegions: 'SADC',
  setSshAllowedRegions: (sshAllowedRegions) => set({ sshAllowedRegions }),
  sshAugmentDefault: true,
  setSshAugmentDefault: (sshAugmentDefault) => set({ sshAugmentDefault }),
  sshLogs: '',
  setSshLogs: (sshLogs) => set({ sshLogs }),
  geoAllowedCountries: '',
  setGeoAllowedCountries: (geoAllowedCountries) => set({ geoAllowedCountries }),
  geoAllowedRegions: 'SADC',
  setGeoAllowedRegions: (geoAllowedRegions) => set({ geoAllowedRegions }),
  geoAugmentDefault: true,
  setGeoAugmentDefault: (geoAugmentDefault) => set({ geoAugmentDefault }),
  editingRegion: null,
  setEditingRegion: (editingRegion) => set({ editingRegion }),
  editingRegionCountries: '',
  setEditingRegionCountries: (editingRegionCountries) => set({ editingRegionCountries }),
  showAddGeoExceptionModal: false,
  setShowAddGeoExceptionModal: (showAddGeoExceptionModal) => set({ showAddGeoExceptionModal }),
  geoExcUsername: '',
  setGeoExcUsername: (geoExcUsername) => set({ geoExcUsername }),
  geoExcService: 'all',
  setGeoExcService: (geoExcService) => set({ geoExcService }),
  geoExcCountries: '',
  setGeoExcCountries: (geoExcCountries) => set({ geoExcCountries }),
  geoExcExpires: '',
  setGeoExcExpires: (geoExcExpires) => set({ geoExcExpires }),
  selectedGeoDomainId: '',
  setSelectedGeoDomainId: (selectedGeoDomainId) => set({ selectedGeoDomainId }),
  geoSubTab: 'mail',
  setGeoSubTab: (geoSubTab) => set({ geoSubTab }),
}));

export default useGeoAuthStore;
