// src/store/useSystemHealthStore.js
import { create } from 'zustand';

const useSystemHealthStore = create((set) => ({
  systemHealth: null,
  setSystemHealth: (systemHealth) => set({ systemHealth }),
  detailedServices: [],
  setDetailedServices: (detailedServices) => set({ detailedServices }),
  servicesLoading: false,
  setServicesLoading: (servicesLoading) => set({ servicesLoading }),
  serviceActionLoading: {},
  setServiceActionLoading: (serviceActionLoading) => set({ serviceActionLoading }),
  configFiles: [],
  setConfigFiles: (configFiles) => set({ configFiles }),
  selectedConfigId: '',
  setSelectedConfigId: (selectedConfigId) => set({ selectedConfigId }),
  configContent: '',
  setConfigContent: (configContent) => set({ configContent }),
  configIsDirty: false,
  setConfigIsDirty: (configIsDirty) => set({ configIsDirty }),
  configLoading: false,
  setConfigLoading: (configLoading) => set({ configLoading }),
  isValidatingConfig: false,
  setIsValidatingConfig: (isValidatingConfig) => set({ isValidatingConfig }),
  configValidation: null,
  setConfigValidation: (configValidation) => set({ configValidation }),
  serverControlTab: 'services',
  setServerControlTab: (serverControlTab) => set({ serverControlTab }),
  logsService: '',
  setLogsService: (logsService) => set({ logsService }),
  serviceRailExpanded: true,
  setServiceRailExpanded: (serviceRailExpanded) => set({ serviceRailExpanded }),
  logsSince: '1h',
  setLogsSince: (logsSince) => set({ logsSince }),
  logsPriority: 'all',
  setLogsPriority: (logsPriority) => set({ logsPriority }),
  logsLimit: '100',
  setLogsLimit: (logsLimit) => set({ logsLimit }),
  logsInterval: 'off',
  setLogsInterval: (logsInterval) => set({ logsInterval }),
  logsQuery: '',
  setLogsQuery: (logsQuery) => set({ logsQuery }),
  autoRefreshLogs: false,
  setAutoRefreshLogs: (autoRefreshLogs) => set({ autoRefreshLogs }),
  serviceLogs: '',
  setServiceLogs: (serviceLogs) => set({ serviceLogs }),
  serviceLogsLoading: false,
  setServiceLogsLoading: (serviceLogsLoading) => set({ serviceLogsLoading }),
}));

export default useSystemHealthStore;
